### ISSUE TITLE
Service 'server' failed to build: The command '/bin/sh -c npm install && npm run build && rm -rf node_modules' returned a non-zero code: 1

### ISSUE THREAD

**Issue by surajrb** [teppeis/redash-client#3]
Getting error as below while trying to install 

`npm ERR! Linux 4.4.93-boot2docker
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! redash-client@3.0.0 build: `rm -rf ./client/dist/ && NODE_ENV=productio
n node node_modules/.bin/webpack`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the redash-client@3.0.0 build script 'rm -rf ./client/dist/ &
& NODE_ENV=production node node_modules/.bin/webpack'.`

**Comment by teppeis** [comment]
Sorry, I cannot repro.
