### ISSUE TITLE
postQuery() does not call /api/queries

### ISSUE THREAD

**Issue by koooge** [teppeis/redash-client#66]
Hi ✋ 
I expected to call `/api/queries` with postQuery(), But redash-client calls `/api/query_results` actually.
https://github.com/teppeis/redash-client/blob/master/src/RedashClient.js#L48
What would you plan to add an API of `POST api/queries`?

**Comment by teppeis** [comment]
@koooge Nice catch!
I've added `postQuery` for `POST /api/query_results` to execute a query initially.
But in Redash, another API `POST /api/queries` exists to ***save*** a query.

In next major update, I will rename existing `postQuery` to `postQueryResult` and add `postQuery` for `POST /api/queries`.

**Comment by teppeis** [comment]
fixed in #69
